# Generated by Django 2.2.17 on 2021-01-29 15:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_reservation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reservation',
            old_name='room_id',
            new_name='room',
        ),
        migrations.AlterUniqueTogether(
            name='reservation',
            unique_together={('room', 'date')},
        ),
    ]
